(function(){
var HDR={Clients:['ID_Client','Nom_Affichage','Prenom','Nom','Entreprise','Statut_Client','Telephone','Email','Adresse_Ligne_1','Code_Postal','Ville','Canal_Obtention','Notes','Archive'],Chantiers:['ID_Chantier','ID_Client','Type_Chantier','Description_Technique','Prix_Defaut','Duree_Estimee','Statut_Chantier','Notes','Archive'],Devis:['ID_Devis','ID_Client','ID_Chantier','ID_Chantiers','Date_Creation','Montant','Statut_Devis','Date_Visite','Heure_Visite','Notes','Archive'],Interventions:['ID_Intervention','ID_Client','ID_Chantier','Date_Prevue','Heure','Duree_Estimee','Montant_Encaisse','Statut_Intervention','ID_Facture','Notes','Archive'],Factures:['ID_Facture','ID_Client','Date_Facture','Interventions','Montant_Total_HT','Statut_Facture','Mode_Reglement','Date_Encaissement','Montant_Encaisse','Notes','Archive'],Relances:['ID_Relance','ID_Client','Date_Relance','Canal','Suivi_Relance','Objet','Notes']};
var META=['Application','Version','Date_Export','Factures'];
function cfg(k,v){try{if(v===undefined)return localStorage.getItem('abp_cloud_'+k)||'';localStorage.setItem('abp_cloud_'+k,v)}catch(e){return ''}}
function toAoa(sheets){var o={};Object.keys(sheets).forEach(function(n){var r=sheets[n],h=r.length?Object.keys(r[0]):(HDR[n]||[]);o[n]=[h].concat(r.map(function(x){return h.map(function(k){var v=x[k];return v==null?'':(typeof v==='object'?JSON.stringify(v):String(v))})}))});return o}
async function api(body){var u=cfg('url'),k=cfg('key');if(!u||!k)throw Error('Renseignez l\u2019URL et la clé.');var r;if(body){r=await fetch(u,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(Object.assign({key:k},body))})}else{r=await fetch(u+(u.indexOf('?')>-1?'&':'?')+'key='+encodeURIComponent(k))}var j=await r.json();if(!j.ok)throw Error(j.error||'Erreur');return j}
function st(t,ok){var e=document.getElementById('cloudmsg');if(e){e.textContent=t;e.style.color=ok===false?'#b43a3a':'#167b55'}}
async function push(){if(!confirm('Envoyer les données de CET appareil vers Google Sheets ? Le contenu des onglets sera remplacé.'))return;try{st('Envoi en cours…');var j=await api({action:'push',sheets:toAoa(buildSheets())});cfg('last',new Date().toLocaleString('fr-FR'));st('Envoyé : '+Object.keys(j.counts).map(function(n){return n+' '+j.counts[n]}).join(', '))}catch(e){st('Échec : '+e.message,false)}}
async function pull(){if(!confirm('Remplacer les données de CET appareil par celles de Google Sheets ?'))return;try{st('Réception…');var j=await api(),d={clients:[],chantiers:[],devis:[],interventions:[],relances:[],factures:[]},sh=j.sheets;Object.keys(sh).forEach(function(n){var l=n.toLowerCase();if(l==='parametres'){if(sh[n][0]){var set={};Object.keys(sh[n][0]).forEach(function(k){if(META.indexOf(k)<0)set[k]=sh[n][0][k]});d.settings=set}return}var x=normalize(n,sh[n]);if(l.includes('client'))d.clients=x;else if(l.includes('chant'))d.chantiers=x;else if(l.includes('devis'))d.devis=x;else if(l.includes('intervention'))d.interventions=x;else if(l.includes('relance'))d.relances=x;else if(l.includes('facture'))d.factures=x});if(!d.clients.length)throw Error('Google Sheets ne contient aucun client.');S.d=d;S.file='Google Sheets';linkInvoices();save();cfg('last',new Date().toLocaleString('fr-FR'));render();st('Reçu : '+d.clients.length+' clients, '+d.chantiers.length+' chantiers, '+d.interventions.length+' interventions.')}catch(e){st('Échec : '+e.message,false)}}
function openPanel(){pop('Synchronisation Google Sheets','<div class="field"><label>URL de l\u2019application web (Apps Script)</label><input id="cl_url" style="width:100%" value="'+esc(cfg('url'))+'"></div><div class="field"><label>Clé secrète</label><input id="cl_key" type="password" style="width:100%" value="'+esc(cfg('key'))+'"></div><p class="small">Dernière synchro : '+esc(cfg('last')||'jamais')+'</p><div style="display:flex;gap:8px;flex-wrap:wrap;margin:12px 0"><button class="btn" id="cl_push">⬆ Envoyer vers Google Sheets</button><button class="btn alt" id="cl_pull">⬇ Récupérer depuis Google Sheets</button></div><div class="small" id="cloudmsg"></div>');var sv=function(){cfg('url',document.getElementById('cl_url').value.trim());cfg('key',document.getElementById('cl_key').value.trim())};document.getElementById('cl_push').onclick=function(){sv();push()};document.getElementById('cl_pull').onclick=function(){sv();pull()}}
var b=document.createElement('button');b.textContent='☁ Cloud';b.setAttribute('style','position:fixed;right:14px;bottom:14px;z-index:50;border:0;border-radius:24px;padding:12px 18px;background:#102038;color:#fff;font-weight:700;box-shadow:0 4px 14px rgba(0,0,0,.25);cursor:pointer');b.onclick=openPanel;document.body.appendChild(b);
})();
